@baseURL = http://localhost:3333
@authToken = {{authenticate.response.body.access_token}}


# @name create_account
POST {{baseURL}}/accounts
Content-Type: application/json

{
  "name": "Renan Loureiro",
  "email": "renanloureiro.dev@gmail.com",
  "password": "12345678"
}

###

# @name authenticate
POST {{baseURL}}/sessions
Content-Type: application/json

{
  "name": "Renan Loureiro",
  "email": "renanloureiro.dev@gmail.com",
  "password": "12345678"
}

###

# @name crete_question
POST {{baseURL}}/questions
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "title": "A new question 3",
  "content": "A new question teste"
}

###

# @name fetch_recente_questions
GET {{baseURL}}/questions?page=1
Content-Type: application/json
Authorization: Bearer {{authToken}}

###
